//go:generate ../../internal/code-gen/code-gen -g eventTypes -p uievents

// Package uievents creates and dispatches [UI Events].
//
// Properties for the different events, like cancelable and bubbles are handled
// by code generated from web IDL specifications, ensuring "correct" bubble and
// cancel behaviour for events.
//
// Due to the autogenerated nature, this includes events that are never
// dispatched.
//
// [UI Events]: https://developer.mozilla.org/en-US/docs/Web/API/UI_Events
package uievents
