// Package clock provides a simulated time for Gost-DOM.
package clock

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"slices"
	"sync/atomic"
	"time"

	"github.com/gost-dom/browser/internal/log"
)

type processEventOptions struct {
	keepCurrentTime bool
}

type ProcessEventOption func(*processEventOptions)

// Deprecated: A better solution exists for the problem this was intended to
// solve. This function has no effect.
func KeepCurrentTime() ProcessEventOption {
	return func(o *processEventOptions) {
		o.keepCurrentTime = true
	}
}

// DefaultEventBufSize is the default capacity used when not specified
// explicitly for the internal channel events pushed to the event loop.
const DefaultEventBufSize = 8

type TaskHandle uint32

// A TaskCallback is the callback registered for a [futureTask].
type TaskCallback func() error
type TaskCallbackContext func(context.Context) error

func (c TaskCallback) call(context.Context) error { return c() }

func (c TaskCallbackContext) call(ctx context.Context) error { return c(ctx) }

type callback interface {
	call(context.Context) error
}

// SafeTask creates a TaskCallback with a nil error from a simple callback
// function which cannot produce an error
func SafeTask(cb func()) TaskCallback { return func() error { cb(); return nil } }

// A futureTask represents a task to run when simulated time advances past the
// specified Time value.
type futureTask struct {
	time   time.Time
	task   callback
	handle TaskHandle
	repeat bool
	delay  time.Duration
	async  bool
}

func (t *futureTask) call(ctx context.Context) error {
	return t.task.call(ctx)
}

func (t futureTask) due(deadline time.Time) bool {
	// Async tasks are not due this tick (causes clock.tick() to deadlock)
	if t.async {
		return t.time.Before(deadline)
	} else {
		return !t.time.After(deadline)
	}
}

// Clock simulates passing of time, as well as potential future tasks. Simulated
// Time can be advanced using [Clock.Advance] or [Clock.RunAll]. The zero value
// for Clock represents Unix time 0, and will not panic.
//
// Advancing time will perform the following
// - Run microtasks.
// - Flush any registered "Flushers"
// - Run timeout/interval callbacks
//
// Microtasks are JavaScript callbacks that should execute when a script has
// completed, but before returning to the event loop. The script engine _may_
// run microtasks, possibly making microtask management unnecessary in this
// space.
//
// Advance and RunAll will return an error if any of the executed tasks return
// an error; Advance and RunAll panics if the task list isn't reducing.
//
// Advancing the clock panics if the task queue isn't decreasing, i.e, tasks are
// adding new tasks. This will happen if a JavaScript call to setInterval isn't
// cleared before calling [RunAll], or a setTimeout callback that continuously
// adds a new immediate callback, or a microtasks creating a new microtask.
//
// This is designed to panic rather than return an error, as an error represents
// an error generated by the code being tested. You may choose to ignore it, or
// even assert on it's presence when testing error conditions. But a task list
// that doesn't decrease is an error, that the developer should be notified of;
// which is why the design is a panic.
//
// The behaviour is configurable by the MaxLoopWithoutDecrement value.
type Clock struct {
	MicrotaskQueue TaskQueue

	Time   time.Time
	Logger *slog.Logger
	Ctx    context.Context

	// Sets the number of times a task is allowed to run without seeing a
	// reduction in task list size. I.e., the task list doesn't need to be
	// emptied after the specified no of tasks executed, but the smallest
	// observed size of the queue must have decreased. The counter is reset
	// every time a new minimum of remaining number of tasks is noticed
	MaxLoopWithoutDecrement int

	// EventBufSize sets the event channel buffer capacity if non-zero.
	// Otherwise [DEFAULT_EVENT_BUF_SIZE] is used.
	EventBufSize int
	tasks        []futureTask
	nextHandle   TaskHandle

	// events are "tasks" that occur outside the script engine in separate
	// goroutines but triggers functions that must run in the "event loop". For
	// example, settling promises when fetch requests succeed.
	events        chan (TaskCallback)
	pendingEvents int

	// stack contains the depth of nested calls to [*Clock.Do], keeping track of
	// when to run microtasks.
	stack int
}

func (c *Clock) runMicrotasks() error { return c.MicrotaskQueue.RunMicrotasks() }

// Creates a new clock. If the options don't set a specific time, the clock is
// initialised with the current system time as the initial simulated wall clock
// time.
//
// If tests depend on an actual time, e.g., verifying a local time displaed in
// the user interface, then test code should pass a concrete starting time;
// letting the test execution be independent of the running environment.
//
// The option should only be left out if the test only needs to verify behaviour
// due to passing of time. E.g., testing throttling/debouncing/timeouts.
func New(options ...NewClockOption) *Clock {
	c := &Clock{
		MaxLoopWithoutDecrement: 100,
	}
	for _, o := range options {
		o(c)
	}
	if c.Time.IsZero() {
		c.Time = time.Now()
	}
	return c
}

func (c *Clock) setLogger(l *slog.Logger) *slog.Logger {
	if l == nil {
		l = log.Default()
	}
	l = l.With("pkg", "gost-dom/clock")
	c.Logger = l
	return l
}

func (c *Clock) logger() *slog.Logger {
	l := c.Logger
	if l == nil {
		l = c.setLogger(nil)
	}
	return l
}

func (c *Clock) peek() (res futureTask, ok bool) {
	if len(c.tasks) > 0 {
		ok = true
		res = c.tasks[0]
	}
	return
}

func (c *Clock) Context() context.Context {
	if c.Ctx != nil {
		return c.Ctx
	}
	return context.Background()
}

func (c *Clock) dequeue() (res *futureTask, ok bool) {
	if len(c.tasks) > 0 {
		ok = true
		res = &c.tasks[0]
		c.tasks = c.tasks[1:]
	}
	return
}

func (c *Clock) runNextTask(ctx context.Context) error {
	task, ok := c.dequeue()
	if !ok {
		return nil
	}
	c.Time = task.time
	if task.repeat {
		task.time = task.time.Add(task.delay)
		c.insertTask(*task)
	}
	return task.call(ctx)
}
func (c *Clock) runWhile(ctx context.Context, predicate func() bool) []error {
	errs := []error{c.runMicrotasks()}

	minLength := len(c.tasks)
	count := 0
	for predicate() {
		if err := c.runNextTask(ctx); err != nil {
			errs = append(errs, err)
		}
		newLength := len(c.tasks)
		if newLength < minLength {
			minLength = newLength
			count = 0
		} else {
			count++
			if count > c.MaxLoopWithoutDecrement {
				panic("Clock: Size of pending tasks isn't decreasing. Are tasks adding new tasks?")
			}
		}
	}
	return errs
}

// Advances the clock by the specified amount of time. Any new tasks being
// registered while running will be executed; if they are scheduled _before_ the
// timeout. When returning, the clock time will be the current time + the
// duration.
//
// Returns an error if any of the added tasks generate an error. Panics if the
// task list doesn't decrease in size. See [Clock] documentation for more info.
func (c *Clock) Advance(d time.Duration) error {
	c.logger().Info("Clock.Advance", "duration", d, "clock", c)
	endTime := c.Time.Add(d)
	errs := []error{c.runMicrotasks()}
	errs = append(errs, c.runWhile(c.Context(), func() bool {
		task, ok := c.peek()
		return ok && !task.time.After(endTime)
	})...)
	c.Time = endTime
	return errors.Join(errs...)
}

func (c *Clock) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("microtasks", c.MicrotaskQueue),
		slog.Int("noTasks", len(c.tasks)),
	)
}

func (c *Clock) enter() { c.stack++ }
func (c *Clock) exit() error {
	if c.stack <= 0 {
		// Not fool-proof, help prevent future code changes resulting in
		// unbalanced enter/exit calls.
		panic("Unbalanced enter/exit calls")
	}
	c.stack--
	if c.stack > 0 {
		return nil
	}
	return c.tick()
}

// Do wraps a task call and runs microtasks when it has completed. Nested tasks
// will not trigger microtasks; only when the original root task completes.
func (c *Clock) Do(f func() error) (err error) {
	c.enter()
	defer func() {
		err = errors.Join(err, c.exit())
	}()

	return f()
}

// tick runs all tasks scheduled for immediate execution. This is synonymous
// with calling Advance(0).
func (c *Clock) tick() error {
	c.logger().Info("Clock.tick", "clock", c)
	endTime := c.Time
	errs := []error{c.runMicrotasks()}
	errs = append(errs, c.runWhile(c.Context(), func() bool {
		task, ok := c.peek()
		return ok && task.due(endTime) // task.due(endTime)
		// return ok && !task.time.After(endTime) // task.due(endTime)
	})...)
	c.Time = endTime
	return errors.Join(errs...)
}

// Cancel removes the task that have been added using [Clock.SetTimeout] or
// [Clock.SetInterval]. This corresponds to either [clearTimeout] or
// [clearInterval] in the browser, which by specification can be used
// interchangably; but shouldn't for clarity.
//
// [clearTimeout]: https://developer.mozilla.org/en-US/docs/Web/API/Window/clearTimeout
// [clearInterval]: https://developer.mozilla.org/en-US/docs/Web/API/Window/clearInterval
func (c *Clock) Cancel(handle TaskHandle) {
	idx := slices.IndexFunc(
		c.tasks,
		func(t futureTask) bool { return t.handle == handle },
	)
	if idx >= 0 {
		c.tasks = slices.Delete(c.tasks, idx, idx+1)
	}
}

// QueueMicrotask adds a task to the "microtask queue".
//
// This shouldn't be called from Go code. Microtasks are a property of
// JavaScript execution and should really be carried out by the javascript
// engine.
func (c *Clock) QueueMicrotask(t TaskCallback) {
	c.MicrotaskQueue.Enqueue(t)
}

// [EventLoopCallback] is used to add an event to the event loop. You must call
// [Clock.BeginEvent] to get an instance, and each instance can only be used for
// one callback. Passing multiple event loop callbacks to the same instance will
// panic.
type EventLoopCallback struct {
	clock *Clock
	used  atomic.Bool
}

// AddEvent allows a goroutine to add an event to be executed on the event loop
// goroutine. This is safe to call from any goroutine.
//
// [EventLoopCallback.AddEvent]/[EventLoopCallback.AddSafeEvent] may only be
// called once. Multiple calls will panic.
func (c *EventLoopCallback) AddEvent(cb TaskCallback) {
	prev := c.used.Swap(true)
	if prev {
		panic("gost-dom/clock: adding multiple callbacks from same BeginEvent() call")
	}
	c.clock.addEvent(cb)
}

// BeginEvent tells the event loop that an event is expected to be added in the
// future. This should be called on the event loop goroutine.
//
// BeginEvent returns an [EventLoopCallback] that the caller must use to pass the
// event to the event loop.
//
// Deprecated: It was discovered that this works poorly; With no information
// about when the callback is expected to arrive, callbacks to detect if
func (c *Clock) BeginEvent() *EventLoopCallback {
	panic("BeginEvent no longer works (it never worked well). A recommended replacement " +
		"is to call SetTimeoutContext with a callback body reading from a channel, " +
		"aborting on ctx.Done() channel",
	)
}

func (c *Clock) addEvent(task TaskCallback) {
	c.logger().Debug("Clock.AddEvent")
	c.events <- task
}

// ProcessEvents processes all pending "events", allowing test cases to wait for a system to "settle"
//
// For most scenarios, the test case merely needs to wait for all these tasks to
// have completed. E.g., a click handler fetches new data and presents it to the
// user, the test case should continue once data is visible.
//
// This function does just that, waits for all these processes to complete.
//
// Warning: There is a glitch in the implementation of this function. setTimeout
// callbacks will be processed before HTTP responses, causing simulated time to
// advance. This could cause client-side timeout logic to be triggered. To prevent
// future tasks to execute, you can pass the [KeepCurrentTime] option; but a better
// solution will be worked on.
//
// Deprecated: The name is likely to change. The term "event" can have different meanings in
// different contexts; so a more precise term will likely be added.
func (c *Clock) ProcessEvents(ctx context.Context, opts ...ProcessEventOption) error {
	return c.processEventsWhile(ctx, func(*[]error) bool {
		_, ok := c.peek()
		return ok
	})
}

// ProcessEvents processes pending events as long as predicate p evaluates to
// true. This is a more granular version of [Clock.ProcessEvents] that has it's
// use when certain expected events cannot have arrived.
//
// An example: Using fetch from JavaScript
//
//	setState("REQUEST")
//	const response = await fetch(url)
//	setState("RESPONSE", response.statusCode)
//	const data = await response.json()
//	setState("SUCCESS", data)
//
// This will create two promises. ProcessEvents would wait for both to
// resolve which would only succeed if the response has been fully generated.
// If you wish proceed until the "RESPONSE" state is set, this function can be
// called with a predicate inspecting the observable side effects of the call to
// setState.
//
//	clock.ProcessEventsWhile(ctx, func() bool {
//		statusIndicator := win.Document().GetElementById("status-indicator")
//		return statusIndicator.TextContent() == "RESPONSE"
//	})
func (c *Clock) ProcessEventsWhile(
	ctx context.Context,
	f func() bool,
	opts ...ProcessEventOption,
) error {
	return c.processEventsWhile(ctx, func(*[]error) bool { return f() })
}

func (c *Clock) processEventsWhile(
	ctx context.Context,
	f func(*[]error) bool,
) error {
	errs := make([]error, 0, 1+c.pendingEvents*2)
	c.logger().Debug("Clock.processEventsWhile", "pendingCount", c.pendingEvents, "this", c)
	for f(&errs) {
		if err := c.runNextTask(ctx); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

func (c *Clock) generateHandle() TaskHandle {
	c.nextHandle++
	return c.nextHandle
}

func (c *Clock) insertTask(future futureTask) TaskHandle {
	if future.handle == 0 {
		future.handle = c.generateHandle()
	}
	idx := slices.IndexFunc(c.tasks, func(t futureTask) bool { return t.time.After(future.time) })
	if idx >= 0 {
		c.tasks = slices.Insert(c.tasks, idx, future)
	} else {
		c.tasks = append(c.tasks, future)
	}
	return future.handle
}

// FutureTime calculates the simulated wall clock in the future given, given the
// current simulated wall clock, and delay d. Panics if d is negative.
func (c *Clock) FutureTime(d time.Duration) time.Time {
	if d < 0 {
		panic(fmt.Sprintf("Clock.SetInterval: negative delay: %d", d))
	}
	return c.Time.Add(d)
}

// SetInterval corresponds to the browser's [setInterval] function. Panics if
// the delay is negative.
//
// [SetInterval]: https://developer.mozilla.org/en-US/docs/Web/API/Window/setInterval
func (c *Clock) SetInterval(task TaskCallback, delay time.Duration) TaskHandle {
	return c.insertTask(
		futureTask{
			time:   c.FutureTime(delay),
			task:   task,
			repeat: true,
			delay:  delay,
		})
}

// SetInterval corresponds to the browser's [setTimeout] function. Panics if the
// delay is negative.
//
// [SetTimeout]: https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout
func (c *Clock) SetTimeout(task TaskCallback, delay time.Duration) TaskHandle {
	return c.insertTask(futureTask{
		time: c.FutureTime(delay),
		task: task,
	})
}

func (c *Clock) SetTimeoutContext(task TaskCallbackContext, delay time.Duration) TaskHandle {
	return c.insertTask(futureTask{
		time:  c.FutureTime(delay),
		task:  task,
		async: true,
	})
}

// QueueMacrotask places a task on the macrotask queue.
func (c *Clock) QueueMacrotask(task TaskCallback) TaskHandle {
	return c.SetTimeout(task, 0)
}

// Keeps running as long as there are tasks in the task queue. New tasks
// appended while running will also run. When returning, the current time will
// be the time of the last executed task.
//
// Returns an error if any of the added tasks generate an error. Panics if the
// task list doesn't decrease in size. See [Clock] documentation for more info.
func (c *Clock) RunAll() error { return c.runAll(c.Context()) }

func (c *Clock) runAll(ctx context.Context) error {
	errs := c.runWhile(ctx, func() bool { return len(c.tasks) > 0 })
	return errors.Join(errs...)
}

/* -------- Options -------- */

// NewClockOption are used to initialize a new [Clock]
type NewClockOption func(*Clock)

func WithLogger(l *slog.Logger) NewClockOption {
	return func(c *Clock) { c.setLogger(l) }
}

// Initializes the clock's simulated time from a concrete [time.Time] value.
func OfTime(t time.Time) NewClockOption {
	return func(c *Clock) {
		c.Time = t
	}
}

// Initializes the clock's simulated time based on an RFC3339 time string.
// Panics if the string is not valid.
//
// This is intended for the use case where the time is a constant in a test
// case, and as such will either fail or succeed consistently. For variable
// input, the caller should parse the time and use [OfTime] instead.
func OfIsoString(iso string) NewClockOption {
	t, err := time.Parse(time.RFC3339, iso)
	if err != nil {
		panic(fmt.Sprintf("clock.IsoTime: error parsing string - %v", err))
	}
	return OfTime(t)
}
