// Package clock provides a simulated time for Gost-DOM.
package clock

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"slices"
	"sync"
	"sync/atomic"
	"time"

	"github.com/gost-dom/browser/internal/log"
)

// DefaultEventBufSize is the default capacity used when not specified
// explicitly for the internal channel events pushed to the event loop.
const DefaultEventBufSize = 8

type TaskHandle uint32

// A TaskCallback is the callback registered for a [futureTask].
type TaskCallback func() error

// SafeTask creates a TaskCallback with a nil error from a simple callback
// function which cannot produce an error
func SafeTask(cb func()) TaskCallback { return func() error { cb(); return nil } }

// A futureTask represents a task to run when simulated time advances past the
// specified Time value.
type futureTask struct {
	time   time.Time
	task   TaskCallback
	handle TaskHandle
	repeat bool
	delay  time.Duration
}

// Clock simulates passing of time, as well as potential future tasks. Simulated
// Time can be advanced using [Clock.Advance] or [Clock.RunAll]. The zero value
// for Clock represents Unix time 0, and will not panic.
//
// Advancing time will perform the following
// - Run microtasks.
// - Flush any registered "Flushers"
// - Run timeout/interval callbacks
//
// Microtasks are JavaScript callbacks that should execute when a script has
// completed, but before returning to the event loop. The script engine _may_
// run microtasks, possibly making microtask management unnecessary in this
// space.
//
// Advance and RunAll will return an error if any of the executed tasks return
// an error; Advance and RunAll panics if the task list isn't reducing.
//
// Advancing the clock panics if the task queue isn't decreasing, i.e, tasks are
// adding new tasks. This will happen if a JavaScript call to setInterval isn't
// cleared before calling [RunAll], or a setTimeout callback that continuously
// adds a new immediate callback, or a microtasks creating a new microtask.
//
// This is designed to panic rather than return an error, as an error represents
// an error generated by the code being tested. You may choose to ignore it, or
// even assert on it's presence when testing error conditions. But a task list
// that doesn't decrease is an error, that the developer should be notified of;
// which is why the design is a panic.
//
// The behaviour is configurable by the MaxLoopWithoutDecrement value.
type singleClock struct {
	MicrotaskQueue TaskQueue

	time   time.Time
	Logger *slog.Logger

	// Sets the number of times a task is allowed to run without seeing a
	// reduction in task list size. I.e., the task list doesn't need to be
	// emptied after the specified no of tasks executed, but the smallest
	// observed size of the queue must have decreased. The counter is reset
	// every time a new minimum of remaining number of tasks is noticed
	MaxLoopWithoutDecrement int

	// EventBufSize sets the event channel buffer capacity if non-zero.
	// Otherwise [DEFAULT_EVENT_BUF_SIZE] is used.
	EventBufSize int
	tasks        []futureTask
	nextHandle   TaskHandle

	// events are "tasks" that occur outside the script engine in separate
	// goroutines but triggers functions that must run in the "event loop". For
	// example, settling promises when fetch requests succeed.
	events        chan (TaskCallback)
	pendingEvents int
	mu            sync.RWMutex
	stack         int
}

func (c *singleClock) runMicrotasks() error { return c.MicrotaskQueue.RunMicrotasks() }

func (c *singleClock) Close() {
	if c.events == nil {
		close(c.events)
		c.events = nil
	}
}

func (c *singleClock) Time() time.Time { return c.time }

func (c *singleClock) setLogger(l *slog.Logger) *slog.Logger {
	if l == nil {
		l = log.Default()
	}
	l = l.With("pkg", "gost-dom/singleClock")
	c.Logger = l
	return l
}

func (c *singleClock) logger() *slog.Logger {
	l := c.Logger
	if l == nil {
		l = c.setLogger(nil)
	}
	return l
}

func (c *singleClock) peek() (res futureTask, ok bool) {
	c.mu.RLock()
	defer c.mu.RUnlock()

	if len(c.tasks) > 0 {
		ok = true
		res = c.tasks[0]
	}
	return
}

func (c *singleClock) dequeue() (res futureTask, ok bool) {
	c.mu.Lock()
	defer c.mu.Unlock()

	if len(c.tasks) > 0 {
		ok = true
		res = c.tasks[0]
		c.tasks = c.tasks[1:]
	}
	return
}

func (c *singleClock) length() int {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return len(c.tasks)
}

func (c *singleClock) runWhile(predicate func() bool) []error {
	var errs []error

	minLength := c.length()
	count := 0
	for predicate() {
		task, ok := c.dequeue()
		if !ok {
			break
		}
		c.time = task.time
		if err := task.task(); err != nil {
			errs = append(errs, err)
		}
		if task.repeat {
			task.time = task.time.Add(task.delay)
			c.insertTask(task)
		}
		newLength := c.length()
		if newLength < minLength {
			minLength = newLength
			count = 0
		} else {
			count++
			if count > c.MaxLoopWithoutDecrement {
				panic(
					"singleClock: Size of pending tasks isn't decreasing. Are tasks adding new tasks?",
				)
			}
		}
	}
	return errs
}

// Advances the clock by the specified amount of time. Any new tasks being
// registered while running will be executed; if they are scheduled _before_ the
// timeout. When returning, the clock time will be the current time + the
// duration.
//
// Returns an error if any of the added tasks generate an error. Panics if the
// task list doesn't decrease in size. See [Clock] documentation for more info.
func (c *singleClock) advance(d time.Duration) error {
	c.logger().Debug("Clock.Advance", "duration", d, "clock", c)
	endTime := c.time.Add(d)
	errs := []error{c.runMicrotasks()}
	errs = append(errs, c.runWhile(func() bool {
		task, ok := c.peek()
		return ok && !task.time.After(endTime)
	})...)
	c.time = endTime
	return errors.Join(errs...)
}

func (c *singleClock) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("microtasks", c.MicrotaskQueue),
		slog.Int("noTasks", c.length()),
	)
}

// Cancel removes the task that have been added using [singleClock.SetTimeout] or
// [singleClock.SetInterval]. This corresponds to either [clearTimeout] or
// [clearInterval] in the browser, which by specification can be used
// interchangably; but shouldn't for clarity.
//
// [clearTimeout]: https://developer.mozilla.org/en-US/docs/Web/API/Window/clearTimeout
// [clearInterval]: https://developer.mozilla.org/en-US/docs/Web/API/Window/clearInterval
func (c *singleClock) Cancel(handle TaskHandle) {
	c.mu.Lock()
	defer c.mu.Unlock()

	idx := slices.IndexFunc(
		c.tasks,
		func(t futureTask) bool { return t.handle == handle },
	)
	if idx >= 0 {
		c.tasks = slices.Delete(c.tasks, idx, idx+1)
	}
}

// QueueMicrotask adds a task to the "microtask queue".
//
// This shouldn't be called from Go code. Microtasks are a property of
// JavaScript execution and should really be carried out by the javascript
// engine.
func (c *singleClock) QueueMicrotask(t TaskCallback) {
	c.MicrotaskQueue.Enqueue(t)
}

// [EventLoopCallback] is used to add an event to the event loop. You must call
// [singleClock.BeginEvent] to get an instance, and each instance can only be used for
// one callback. Passing multiple event loop callbacks to the same instance will
// panic.
type EventLoopCallback struct {
	clock *singleClock
	used  atomic.Bool
}

// AddEvent allows a goroutine to add an event to be executed on the event loop
// goroutine. This is safe to call from any goroutine.
//
// [EventLoopCallback.AddEvent]/[EventLoopCallback.AddSafeEvent] may only be
// called once. Multiple calls will panic.
func (c *EventLoopCallback) AddEvent(cb TaskCallback) {
	prev := c.used.Swap(true)
	if prev {
		panic("gost-dom/clock: adding multiple callbacks from same BeginEvent() call")
	}
	c.clock.addEvent(cb)
}

// BeginEvent tells the event loop that an event is expected to be added in the
// future. This should be called on the event loop goroutine.
//
// BeginEvent returns an [EventLoopCallback] that the caller must use to pass the
// event to the event loop.
func (c *singleClock) BeginEvent() *EventLoopCallback {
	c.logger().Debug("singleClock.BeginEvent")

	c.pendingEvents++
	if c.events == nil {
		bufSize := c.EventBufSize
		if bufSize == 0 {
			bufSize = DefaultEventBufSize
		}
		c.events = make(chan TaskCallback, bufSize)
	}
	return &EventLoopCallback{clock: c}
}

func (c *singleClock) addEvent(task TaskCallback) {
	c.logger().Debug("singleClock.AddEvent")
	c.events <- task
}

func (c *singleClock) runDueTasks() []error {
	return c.runWhile(func() bool {
		return len(c.tasks) > 0 && !c.tasks[0].time.After(c.Time())
	})
}

func (c *singleClock) wrapFn(f func() bool, opts ...ProcessEventOption) func(*[]error) bool {
	var opt processEventOptions
	for _, oo := range opts {
		oo(&opt)
	}
	return func(errs *[]error) bool {
		if opt.keepCurrentTime {
			*errs = append(*errs, c.runDueTasks()...)
		} else {
			*errs = append(*errs, RunAll(c))
		}
		return f()
	}
}

// ProcessEvents processes all enqueued tasks and all pending events.
func (c *singleClock) ProcessEvents(ctx context.Context, opts ...ProcessEventOption) error {
	return c.processEventsWhile(
		ctx,
		c.wrapFn(func() bool { return c.pendingEvents > 0 }, opts...),
		"ProcessEvents",
	)
}

func (c *singleClock) ProcessPendingEvents(ctx context.Context, opts ...ProcessEventOption) error {
	return c.processEventsWhile(
		ctx,
		c.wrapFn(func() bool { return c.pendingEvents > 0 }, opts...),
		"ProcessEvents",
	)
}

// ProcessEvents processes pending events as long as predicate p evaluates to
// true. This is a more granular version of [singleClock.ProcessEvents] that has it's
// use when certain expected events cannot have arrived.
//
// An example: Using fetch from JavaScript
//
//	setState("REQUEST")
//	const response = await fetch(url)
//	setState("RESPONSE", response.statusCode)
//	const data = await response.json()
//	setState("SUCCESS", data)
//
// This will create two promises. ProcessEvents would wait for both to
// resolve which would only succeed if the response has been fully generated.
// If you wish proceed until the "RESPONSE" state is set, this function can be
// called with a predicate inspecting the observable side effects of the call to
// setState.
//
//	clock.ProcessEventsWhile(ctx, func() bool {
//		statusIndicator := win.Document().GetElementById("status-indicator")
//		return statusIndicator.TextContent() == "RESPONSE"
//	})
func (c *singleClock) ProcessEventsWhile(
	ctx context.Context,
	f func() bool,
	opt ...ProcessEventOption,
) error {
	return c.processEventsWhile(ctx, c.wrapFn(f, opt...), "ProcessEventsWhile")
}

func (c *singleClock) processEventsWhile(
	ctx context.Context,
	f func(*[]error) bool,
	name string,
) error {
	errs := make([]error, 0, 1+c.pendingEvents*2)
	c.logger().Debug("singleClock.processEventsWhile", "pendingCount", c.pendingEvents, "this", c)
	for f(&errs) {
		c.logger().Debug("singleClock.ProcessEvents: waiting")
		select {
		case event := <-c.events:
			c.pendingEvents--
			err := event()
			c.logger().
				Debug("clock.ProcessEvent: processed", "pendingCount", c.pendingEvents, log.ErrAttr(err))
			errs = append(errs, err)
		case <-ctx.Done():
			return fmt.Errorf("singleClock.%s: timeout waiting for event", name)
		}
	}
	return errors.Join(errs...)
}

func (c *singleClock) generateHandle() TaskHandle {
	c.nextHandle++
	return c.nextHandle
}

func (c *singleClock) insertTask(future futureTask) TaskHandle {
	c.mu.Lock()
	defer c.mu.Unlock()

	if future.handle == 0 {
		future.handle = c.generateHandle()
	}
	idx := slices.IndexFunc(c.tasks, func(t futureTask) bool { return t.time.After(future.time) })
	if idx >= 0 {
		c.tasks = slices.Insert(c.tasks, idx, future)
	} else {
		c.tasks = append(c.tasks, future)
	}
	return future.handle
}

// SetInterval corresponds to the browser's [setInterval] function. Panics if
// the delay is negative.
//
// [SetInterval]: https://developer.mozilla.org/en-US/docs/Web/API/Window/setInterval
func (c *singleClock) SetInterval(task TaskCallback, delay time.Duration) TaskHandle {
	if delay < 0 {
		panic(fmt.Sprintf("singleClock.SetInterval: negative delay: %d", delay))
	}
	return c.insertTask(
		futureTask{
			time:   c.time.Add(delay),
			task:   task,
			repeat: true,
			delay:  delay,
		})
}

// SetInterval corresponds to the browser's [setTimeout] function. Panics if the
// delay is negative.
//
// [SetTimeout]: https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout
func (c *singleClock) SetTimeout(task TaskCallback, delay time.Duration) TaskHandle {
	if delay < 0 {
		panic(fmt.Sprintf("singleClock.SetTimeout: negative delay: %d", delay))
	}
	return c.insertTask(futureTask{
		time: c.time.Add(delay),
		task: task,
	})
}

// QueueMacrotask places a task on the macrotask queue.
func (c *singleClock) QueueMacrotask(task TaskCallback) TaskHandle {
	return c.SetTimeout(task, 0)
}

/* -------- Options -------- */

// NewClockOption are used to initialize a new [singleClock]
type NewClockOption func(*singleClock)

func WithLogger(l *slog.Logger) NewClockOption {
	return func(c *singleClock) { c.setLogger(l) }
}

// Initializes the clock's simulated time from a concrete [time.Time] value.
func OfTime(t time.Time) NewClockOption {
	return func(c *singleClock) {
		c.time = t
	}
}

// Initializes the clock's simulated time based on an RFC3339 time string.
// Panics if the string is not valid.
//
// This is intended for the use case where the time is a constant in a test
// case, and as such will either fail or succeed consistently. For variable
// input, the caller should parse the time and use [OfTime] instead.
func OfIsoString(iso string) NewClockOption {
	t, err := time.Parse(time.RFC3339, iso)
	if err != nil {
		panic(fmt.Sprintf("clock.IsoTime: error parsing string - %v", err))
	}
	return OfTime(t)
}

func (c *singleClock) enter() { c.stack++ }

func (c *singleClock) exit() error {
	if c.stack <= 0 {
		// Not fool-proof, help prevent future code changes resulting in
		// unbalanced enter/exit calls.
		panic("Unbalanced enter/exit calls")
	}
	c.stack--
	if c.stack > 0 {
		return nil
	}
	return Tick(c)
}
