package internal

import (
	"github.com/gost-dom/browser/scripting/internal/dom"
	"github.com/gost-dom/browser/scripting/internal/fileapi"
	"github.com/gost-dom/browser/scripting/internal/html"
	"github.com/gost-dom/browser/scripting/internal/js"
	"github.com/gost-dom/browser/scripting/internal/mathml"
	"github.com/gost-dom/browser/scripting/internal/svg"
)

type ScriptEngineConfigurer[T any] struct {
	initializers []js.Configurer[T]
}

func NewScriptEngineConfigurer[T any](i ...js.Configurer[T]) *ScriptEngineConfigurer[T] {
	return &ScriptEngineConfigurer[T]{i}
}

func (c *ScriptEngineConfigurer[T]) AddConfigurer(configurer js.Configurer[T]) {
	c.initializers = append(c.initializers, configurer)
}

func (c *ScriptEngineConfigurer[T]) AddConfigurerFunc(f func(js.ScriptEngine[T])) {
	c.initializers = append(c.initializers, js.ConfigurerFunc[T](f))
}

func configureNatives[T any](e js.ScriptEngine[T]) {
	e.SetUnhandledPromiseRejectionHandler(
		js.ErrorHandlerFunc[T](handleUnhandledPromiseRejection[T]),
	)
	configureConsole(e)
}

func (c *ScriptEngineConfigurer[T]) Configure(e js.ScriptEngine[T]) {
	for _, i := range c.initializers {
		i.Configure(e)
	}
}

func handleUnhandledPromiseRejection[T any](scope js.Scope[T], err error) {
	dom.HandleJSCallbackError(scope, "promiseRejected", err)
}

// CreateWindowsConfigurer returns a Configurer implementation that initializes
// the Window realm. Most of the initialization is auto-generated from web-IDL
// specs.
func CreateWindowsConfigurer[T any]() *ScriptEngineConfigurer[T] {
	result := NewScriptEngineConfigurer[T]()
	// Basic script enging configuration, set unhandled promise rejection
	// handler, and console logs
	result.AddConfigurerFunc(configureNatives)
	result.AddConfigurerFunc(dom.ConfigureErrors)

	// Autogenerated
	result.AddConfigurerFunc(ConfigureWindowRealm)

	// Additional values to install in global scope that arent yet handled by
	// the code generator.
	result.AddConfigurerFunc(fileapi.ConfigureWindowRealm)
	result.AddConfigurerFunc(InstallPolyfills)
	result.AddConfigurerFunc(svg.ConfigureScriptEngine)
	result.AddConfigurerFunc(mathml.ConfigureScriptEngine)
	result.AddConfigurerFunc(html.ConfigureScriptEngine)
	result.AddConfigurerFunc(dom.ConfigureScriptEngine)
	return result
}
