name: Build

on:
  workflow_call:
  push:
    branches: ["main", "auto-merge", "test/wpt-update"]

jobs:
  build:
    name: Run Web Platform Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'internal/test/wpt/go.mod'
        cache-dependency-path: 'internal/test/wpt/go.sum'
    - name: Run Web Platform Tests
      run: |
        cd internal/test/wpt 
        ./ci
